### PR TITLE
Ported Serialized class from rxjava-extras to FlowableSerialized

### PR DESCRIPTION
**Pull request by janbols**
Ported Serialized class from rxjava-extras to FlowableSerialized.
I didn't create an ObservableSerialized alternative because I assume when doing serialization/deserialization you will probably want to use a Flowable instead of an Observable.

### CODE REVIEW

**Comment by davidmoten** [comment]
thanks for the contribution! more review a bit later.

**Comment by davidmoten** [comment]
sorry about the delay,  missed seeing your changes somehow. Anyway, thanks for this PR.

**Comment by davidmoten** [comment]
@janbols  in addition to the minor changes in the above commits I've moved the class to a `flowable` package so we can give it the shorter name of `Serialized`.   rxjava2-extras 0.1.3 with your `Serialized` addition has gone to Maven Central and will be available there 10 minutes from now (that's the normal delay).

**Comment by janbols** [comment]
Ok, that makes sense. Thanks

**Pull request merged**
